#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local url_fabio="https://github.com/fabiolb/fabio/releases/download/v${FABIO_VERSION}/fabio-${FABIO_VERSION}-go1.9.1-darwin_amd64"
  local fnm_fabio="$(basename "$url_fabio")"

  cache curl "$fnm_fabio" "$url_fabio"

  mkdir -p "$shome/vendor"

  rsync -ia "${CACHE_DIR}/curl/$fnm_fabio" "$shome/vendor/"
  chmod 755 "$shome/vendor/$fnm_fabio"
  mkdir -p "$shome/bin"
  ln -nfs "../vendor/$fnm_fabio" "$shome/bin/fabio"
}

bootstrap
