#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_fabio="$(fabio --version 2>/dev/null || true)"
  jq -n --arg fabio "$ver_fabio" '{fabio: $fabio}'
}

version "$@"
